### ISSUE TITLE
support for the latest version of packetevents.

### ISSUE THREAD

**Issue by whenriquelsh** [MegavexNetwork/scoreboard-library#82]
Hello, so far the lib only supports up to version 2.5.6 of packetevents.

**Comment by vytskalt** [comment]
Were there breaking changes in packetevents since 2.5.6?

**Comment by vytskalt** [comment]
I tried the latest PacketEvents version (2.7.0) and it worked fine on 1.21.4. What issues are you having?

**Comment by whenriquelsh** [comment]
[21:31:38 WARN]: Exception in thread "Craft Scheduler Thread - 2"
[21:31:38 WARN]: org.apache.commons.lang.UnhandledException: Plugin VoxyLegacys v1.0-SNAPSHOT generated an exception while executing task 13
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.NoSuchMethodError: 'void com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerScoreboardObjective.<init>(java.lang.String, com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerScoreboardObjective$ObjectiveMode, apis.adventure.text.Component, com.github.retrooper.packetevents.wrapper.play.server.WrapperPlayServerScoreboardObjective$RenderType, com.github.retrooper.packetevents.protocol.score.ScoreFormat)'
        at apis.scoreboardlibrary.implementation.packetAdapter.packetevents.ObjectivePacketAdapterImpl.createObjectivePacket(ObjectivePacketAdapterImpl.java:154)
        at apis.scoreboardlibrary.implementation.packetAdapter.packetevents.ObjectivePacketAdapterImpl.lambda$sendProperties$0(ObjectivePacketAdapterImpl.java:58)
        at apis.scoreboardlibrary.implementation.packetAdapter.util.LocalePacketUtil.sendLocalePackets(LocalePacketUtil.java:29)
        at apis.scoreboardlibrary.implementation.packetAdapter.packetevents.ObjectivePacketAdapterImpl.sendProperties(ObjectivePacketAdapterImpl.java:55)
        at apis.scoreboardlibrary.implementation.sidebar.AbstractSidebar.display(AbstractSidebar.java:171)
        at apis.scoreboardlibrary.implementation.player.DisplayableQueue.add(DisplayableQueue.java:38)
        at apis.scoreboardlibrary.implementation.sidebar.AbstractSidebar.tick(AbstractSidebar.java:198)
        at apis.scoreboardlibrary.implementation.sidebar.SidebarUpdaterTask.run(SidebarUpdaterTask.java:36)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 4 more
